// src/app/LayoutClient.tsx
"use client";

import { BerforeLoginHeader } from "@/components/layout/BeforeLoginHeader";
import { AfterLoginHeader } from "@/components/layout/AfterLoginHeader";
import { Footer } from "@/components/layout/Footer";
import { useAuth } from "@/hooks/useAuth";
import { usePathname } from "next/navigation";

import { LayoutModeProvider } from "@/components/layout/LayoutModeContext";
import { FriendsNetworkProvider } from "@/contexts/FriendsNetworkContext";
import { UserLocationProvider } from "@/contexts/UserLocationContext";

interface LayoutClientProps {
  children: React.ReactNode;
  /** True when the request came from bloggo.linkedspaces.com (set by middleware). */
  isBloggoDomain: boolean;
  /** Tailwind font-variable class string generated by next/font in the server layout. */
  fontVariables: string;
}

export default function LayoutClient({
  children,
  isBloggoDomain,
  fontVariables,
}: LayoutClientProps) {
  const { isAuthenticated } = useAuth();
  const pathname = usePathname();

  const isAuthPage = pathname === "/sign-in";

  // Treat as bloggo if the path starts with /bloggo OR the request is from
  // the bloggo subdomain (detected server-side via middleware header).
  const isBloggo = (pathname?.startsWith("/bloggo") ?? false) || isBloggoDomain;

  const forceLightTheme =
    pathname === "/" ||
    pathname === "/privacy" ||
    pathname === "/contact" ||
    pathname === "/terms" ||
    pathname === "/home" ||
    pathname === "/explore" ||
    pathname === "/profile" ||
    pathname === "/learn-more" ||
    isBloggo ||
    (pathname?.startsWith("/profile/") ?? false);

  return (
    <html
      lang="en"
      className={`${fontVariables} ${forceLightTheme ? "theme-light" : ""}`}
    >
      <body className="min-h-screen flex flex-col overflow-x-hidden">
        <LayoutModeProvider>
          <UserLocationProvider>
            <FriendsNetworkProvider>
              {!isAuthPage &&
                !isBloggo &&
                (isAuthenticated ? (
                  <AfterLoginHeader />
                ) : (
                  <BerforeLoginHeader />
                ))}

              {isBloggo ? (
                <div className="flex-1">{children}</div>
              ) : (
                <main className="flex-1">{children}</main>
              )}

              {!isAuthenticated && !isBloggo && <Footer />}
            </FriendsNetworkProvider>
          </UserLocationProvider>
        </LayoutModeProvider>
      </body>
    </html>
  );
}
